### ISSUE TITLE
GraphNetwork epochCount is always 0

### ISSUE THREAD

**Issue by RickyEsclapon** [graphprotocol/graph-network-analytics-subgraph#17]
Hello! This is a _really_ tiny issue, but figured it would still be good to call-out.

When querying the analytics subgraph, looking at `graphNetwork` the `epochCount` is always 0:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/89109989/132988389-247f70a0-9aff-43c8-9898-542ea6558809.png">

Bug is specific to the analytics subgraph of course. When I noticed two days ago, I'm pretty sure `subgraphCount` was also showing a value of 0, but seems to be working totally fine now.

Sorry for the call-out to such a small and low-priority issue and you might already be aware of it, but figured it was worth mentioning.

**Comment by juanmardefago** [comment]
Yeah, it's because I forgot to delete those fields on the initial cleanup for analytics (analytics is based off the network subgraph), since those fields weren't needed at all back then.

It might be good to revisit whether they are gonna be needed for the analytics in the future, but adding the logic to track this would most likely impact performance, so I'd only consider adding them if they are completely needed.

I removed some of them (if not all) on the network wide daily data PR (#16 )

Thanks for reporting this, since I just noticed it when working on task 16.

**Comment by RickyEsclapon** [comment]
Makes sense, thank you @juanmardefago! We are definitely good without them since they are tracked through the other subgraph, but maybe worth calling it out in the schema as not implemented or just removing it. But yea definitely not important, just wanted to make you aware in case you weren't 🙂
